# Production Environment Configuration
environment: production
debug: false
log_level: INFO

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  reload: false
  workers: 4

# LLM Configuration
llm:
  provider: "openai"
  model: "gpt-4"
  temperature: 0.3
  max_tokens: 2000
  timeout: 60

# Database Configuration
database:
  url: "${DATABASE_URL}"
  echo: false
  pool_size: 20
  pool_timeout: 30
  pool_recycle: 3600

# Redis Configuration
redis:
  host: "${REDIS_HOST}"
  port: 6379
  db: 0
  password: "${REDIS_PASSWORD}"
  ssl: true

# Monitoring
monitoring:
  metrics_enabled: true
  tracing_enabled: true
  sample_rate: 0.1
  prometheus_port: 9090

# Security
security:
  cors_origins: ["${ALLOWED_ORIGINS}"]
  api_key_required: true
  jwt_secret: "${JWT_SECRET}"
  rate_limiting_enabled: true

# Pipeline Defaults
pipeline_defaults:
  timeout: 300
  max_retries: 5
  cache_enabled: true
  cache_ttl: 7200

# Rate Limiting
rate_limiting:
  enabled: true
  requests_per_minute: 100
  burst_size: 20
  
# Health Checks
health_checks:
  enabled: true
  interval: 30
  timeout: 10 